/*
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

package main

import "fmt"

func main() {
	const MaxTerm = 4000000
	var sum int
	a := 0
	b := 1

	for termNumber := 1; ; termNumber++ {
		fib := a + b
		if fib > MaxTerm {
			break
		}
		if fib%2 == 0 {
			sum += fib
		}
		a = b
		b = fib
		fmt.Printf("%d) %d\n", termNumber, fib)
	}
	fmt.Printf("Total of even terms: %d\n", sum)
}
